# Generated by Django 5.0.6 on 2024-06-11 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del proyecto')),
                ('project_name', models.CharField(max_length=300, unique=True, verbose_name='Nombre del proyecto')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='Descripción del proyecto')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id_project'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la tarea')),
                ('task_name', models.CharField(max_length=300, verbose_name='Nombre de la tarea')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='Descripción de la tarea')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['id_task'],
            },
        ),
    ]
