apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  labels:
    app: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: christianv2426/backend-infraestructuras

        ports:
          - name: http
            containerPort: 8000

        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SECRET_KEY
        
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DEBUG
        
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_NAME
          
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_USER
        
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_PASSWORD
        
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_HOST

        - name: DATABASE_PORT
          value: '5432'

---

apiVersion: v1
kind: Service

metadata:
  name: backend-service

spec:
  type: NodePort

  selector:
    app: backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100

---

apiVersion: v1
kind: Service

metadata:
  name: api-service

spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http
